//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace pfr.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ФайлПФР {
        
        private string имяФайлаField;
        
        private ЗаголовокФайла заголовокФайлаField;
        
        private ПачкаВходящихДокументов пачкаВходящихДокументовField;
        
        /// <remarks/>
        public string ИмяФайла {
            get {
                return this.имяФайлаField;
            }
            set {
                this.имяФайлаField = value;
            }
        }
        
        /// <remarks/>
        public ЗаголовокФайла ЗаголовокФайла {
            get {
                return this.заголовокФайлаField;
            }
            set {
                this.заголовокФайлаField = value;
            }
        }
        
        /// <remarks/>
        public ПачкаВходящихДокументов ПачкаВходящихДокументов {
            get {
                return this.пачкаВходящихДокументовField;
            }
            set {
                this.пачкаВходящихДокументовField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ЗаголовокФайла {
        
        private string версияФорматаField;
        
        private string типФайлаField;
        
        private ПрограммаПодготовкиДанных программаПодготовкиДанныхField;
        
        private string источникДанныхField;
        
        /// <remarks/>
        public string ВерсияФормата {
            get {
                return this.версияФорматаField;
            }
            set {
                this.версияФорматаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string ТипФайла {
            get {
                return this.типФайлаField;
            }
            set {
                this.типФайлаField = value;
            }
        }
        
        /// <remarks/>
        public ПрограммаПодготовкиДанных ПрограммаПодготовкиДанных {
            get {
                return this.программаПодготовкиДанныхField;
            }
            set {
                this.программаПодготовкиДанныхField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string ИсточникДанных {
            get {
                return this.источникДанныхField;
            }
            set {
                this.источникДанныхField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ПрограммаПодготовкиДанных {
        
        private string названиеПрограммыField;
        
        private string версияField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string НазваниеПрограммы {
            get {
                return this.названиеПрограммыField;
            }
            set {
                this.названиеПрограммыField = value;
            }
        }
        
        /// <remarks/>
        public string Версия {
            get {
                return this.версияField;
            }
            set {
                this.версияField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ПачкаВходящихДокументов {
        
        private ВХОДЯЩАЯ_ОПИСЬ вХОДЯЩАЯ_ОПИСЬField;
        
        private ОПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕ оПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕField;
        
        private string доставочнаяОрганизацияField;
        
        /// <remarks/>
        public ВХОДЯЩАЯ_ОПИСЬ ВХОДЯЩАЯ_ОПИСЬ {
            get {
                return this.вХОДЯЩАЯ_ОПИСЬField;
            }
            set {
                this.вХОДЯЩАЯ_ОПИСЬField = value;
            }
        }
        
        /// <remarks/>
        public ОПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕ ОПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕ {
            get {
                return this.оПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕField;
            }
            set {
                this.оПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string ДоставочнаяОрганизация {
            get {
                return this.доставочнаяОрганизацияField;
            }
            set {
                this.доставочнаяОрганизацияField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ВХОДЯЩАЯ_ОПИСЬ {
        
        private string номерВпачкеField;
        
        private string типВходящейОписиField;
        
        private СоставительПачки составительПачкиField;
        
        private НомерПачки номерПачкиField;
        
        private СоставДокументов составДокументовField;
        
        private string датаСоставленияField;
        
        private ТерриториальныйОрганПФР территориальныйОрганПФРField;

        //private string номерБанкаField;
        
        private Банк банкField;
        
        private string системныйНомерМассиваField;
        
        private string месяцField;
        
        private string годField;
        
        private decimal общаяСуммаПоМассивуField;
        
        private string общееКоличествоПорученийПоМассивуField;
        
        private string количествоЧастейМассиваField;
        
        private string должностьField;
        
        private string руководительField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string НомерВпачке {
            get {
                return this.номерВпачкеField;
            }
            set {
                this.номерВпачкеField = value;
            }
        }
        
        /// <remarks/>
        public string ТипВходящейОписи {
            get {
                return this.типВходящейОписиField;
            }
            set {
                this.типВходящейОписиField = value;
            }
        }
        
        /// <remarks/>
        public СоставительПачки СоставительПачки {
            get {
                return this.составительПачкиField;
            }
            set {
                this.составительПачкиField = value;
            }
        }
        
        /// <remarks/>
        public НомерПачки НомерПачки {
            get {
                return this.номерПачкиField;
            }
            set {
                this.номерПачкиField = value;
            }
        }
        
        /// <remarks/>
        public СоставДокументов СоставДокументов {
            get {
                return this.составДокументовField;
            }
            set {
                this.составДокументовField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string ДатаСоставления {
            get {
                return this.датаСоставленияField;
            }
            set {
                this.датаСоставленияField = value;
            }
        }
        
        /// <remarks/>
        public ТерриториальныйОрганПФР ТерриториальныйОрганПФР {
            get {
                return this.территориальныйОрганПФРField;
            }
            set {
                this.территориальныйОрганПФРField = value;
            }
        }

        //public string НомерБанка
        //{
        //    get
        //    {
        //        return this.номерБанкаField;
        //    }
        //    set
        //    {
        //        this.номерБанкаField = value;
        //    }
        //}
        
        /// <remarks/>
        public Банк Банк {
            get {
                return this.банкField;
            }
            set {
                this.банкField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string СистемныйНомерМассива {
            get {
                return this.системныйНомерМассиваField;
            }
            set {
                this.системныйНомерМассиваField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Месяц {
            get {
                return this.месяцField;
            }
            set {
                this.месяцField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Год {
            get {
                return this.годField;
            }
            set {
                this.годField = value;
            }
        }
        
        /// <remarks/>
        public decimal ОбщаяСуммаПоМассиву {
            get {
                return this.общаяСуммаПоМассивуField;
            }
            set {
                this.общаяСуммаПоМассивуField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ОбщееКоличествоПорученийПоМассиву {
            get {
                return this.общееКоличествоПорученийПоМассивуField;
            }
            set {
                this.общееКоличествоПорученийПоМассивуField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string КоличествоЧастейМассива {
            get {
                return this.количествоЧастейМассиваField;
            }
            set {
                this.количествоЧастейМассиваField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Должность {
            get {
                return this.должностьField;
            }
            set {
                this.должностьField = value;
            }
        }
        
        /// <remarks/>
        public string Руководитель {
            get {
                return this.руководительField;
            }
            set {
                this.руководительField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class СоставительПачки {
        
        private НалоговыйНомер налоговыйНомерField;
        
        private string наименованиеОрганизацииField;
        
        private string регистрационныйНомерField;
        
        /// <remarks/>
        public НалоговыйНомер НалоговыйНомер {
            get {
                return this.налоговыйНомерField;
            }
            set {
                this.налоговыйНомерField = value;
            }
        }
        
        /// <remarks/>
        public string НаименованиеОрганизации {
            get {
                return this.наименованиеОрганизацииField;
            }
            set {
                this.наименованиеОрганизацииField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string РегистрационныйНомер {
            get {
                return this.регистрационныйНомерField;
            }
            set {
                this.регистрационныйНомерField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class НалоговыйНомер {
        
        private string иННField;
        
        private string кППField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ИНН {
            get {
                return this.иННField;
            }
            set {
                this.иННField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string КПП {
            get {
                return this.кППField;
            }
            set {
                this.кППField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class НомерПачки {
        
        private string основнойField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Основной {
            get {
                return this.основнойField;
            }
            set {
                this.основнойField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class СоставДокументов {
        
        private string количествоField;
        
        private НаличиеДокументов наличиеДокументовField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Количество {
            get {
                return this.количествоField;
            }
            set {
                this.количествоField = value;
            }
        }
        
        /// <remarks/>
        public НаличиеДокументов НаличиеДокументов {
            get {
                return this.наличиеДокументовField;
            }
            set {
                this.наличиеДокументовField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class НаличиеДокументов {
        
        private string типДокументаField;
        
        private string количествоField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string ТипДокумента {
            get {
                return this.типДокументаField;
            }
            set {
                this.типДокументаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Количество {
            get {
                return this.количествоField;
            }
            set {
                this.количествоField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ТерриториальныйОрганПФР {
        
        private НалоговыйНомер налоговыйНомерField;
        
        private string наименованиеОрганизацииField;
        
        private string регистрационныйНомерField;
        
        /// <remarks/>
        public НалоговыйНомер НалоговыйНомер {
            get {
                return this.налоговыйНомерField;
            }
            set {
                this.налоговыйНомерField = value;
            }
        }
        
        /// <remarks/>
        public string НаименованиеОрганизации {
            get {
                return this.наименованиеОрганизацииField;
            }
            set {
                this.наименованиеОрганизацииField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string РегистрационныйНомер {
            get {
                return this.регистрационныйНомерField;
            }
            set {
                this.регистрационныйНомерField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Банк {
        
        private string наименованиеОрганизацииField;
        
        /// <remarks/>
        public string НаименованиеОрганизации {
            get {
                return this.наименованиеОрганизацииField;
            }
            set {
                this.наименованиеОрганизацииField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ОПИСЬ_ПЕРЕДАВАЕМЫХ_ФАЙЛОВ_НА_ЗАЧИСЛЕНИЕ {
        
        private string номерВпачкеField;
        
        private string количествоПередаваемыхФайловField;
        
        private ПередаваемыйФайл[] передаваемыйФайлField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string НомерВпачке {
            get {
                return this.номерВпачкеField;
            }
            set {
                this.номерВпачкеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string КоличествоПередаваемыхФайлов {
            get {
                return this.количествоПередаваемыхФайловField;
            }
            set {
                this.количествоПередаваемыхФайловField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПередаваемыйФайл")]
        public ПередаваемыйФайл[] ПередаваемыйФайл {
            get {
                return this.передаваемыйФайлField;
            }
            set {
                this.передаваемыйФайлField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ПередаваемыйФайл {
        
        private string типДокументаField;
        
        private string имяФайлаField;
        
        private string количествоПолучателейField;
        
        private string номерЧастиField;
        
        private decimal суммаПоЧастиМассиваField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string ТипДокумента {
            get {
                return this.типДокументаField;
            }
            set {
                this.типДокументаField = value;
            }
        }
        
        /// <remarks/>
        public string ИмяФайла {
            get {
                return this.имяФайлаField;
            }
            set {
                this.имяФайлаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string КоличествоПолучателей {
            get {
                return this.количествоПолучателейField;
            }
            set {
                this.количествоПолучателейField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string НомерЧасти {
            get {
                return this.номерЧастиField;
            }
            set {
                this.номерЧастиField = value;
            }
        }
        
        /// <remarks/>
        public decimal СуммаПоЧастиМассива {
            get {
                return this.суммаПоЧастиМассиваField;
            }
            set {
                this.суммаПоЧастиМассиваField = value;
            }
        }
    }
}
