USE [master]
GO

/****** Object:  Database [pfr]    Script Date: 25.03.2020 15:41:39 ******/
CREATE DATABASE [pfr] ON  PRIMARY 
( NAME = N'pfr', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\pfr.mdf' , SIZE = 57344KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'pfr_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\pfr_log.ldf' , SIZE = 7616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [pfr] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pfr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pfr] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pfr] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pfr] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pfr] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pfr] SET ARITHABORT OFF 
GO

ALTER DATABASE [pfr] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [pfr] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pfr] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pfr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pfr] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pfr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pfr] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pfr] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pfr] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pfr] SET  DISABLE_BROKER 
GO

ALTER DATABASE [pfr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pfr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pfr] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pfr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pfr] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pfr] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pfr] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pfr] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [pfr] SET  MULTI_USER 
GO

ALTER DATABASE [pfr] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pfr] SET DB_CHAINING OFF 
GO

ALTER DATABASE [pfr] SET  READ_WRITE 
GO

