//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoSet
    {
        public DoSet()
        {
            this.UserSet = new HashSet<UserSet>();
        }
    
        public string Kod { get; set; }
        public string Name { get; set; }
        public string Acc47422 { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<UserSet> UserSet { get; set; }
    }
}
