//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoSet
    {
        public DoSet()
        {
            this.UserSet = new HashSet<UserSet>();
        }
    
        public string Kod { get; set; }
        public string Name { get; set; }
        public string Acc47422 { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<UserSet> UserSet { get; set; }
    }
}
