//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpisSet
    {
        public OpisSet()
        {
            this.SpisSet = new HashSet<SpisSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateReg { get; set; }
        public string FileName { get; set; }
        public string Xml { get; set; }
        public string FileName1 { get; set; }
        public string Xml1 { get; set; }
        public string FileName2 { get; set; }
        public string Xml2 { get; set; }
        public string FileName3 { get; set; }
        public string Xml3 { get; set; }
        public string NumMassiv { get; set; }
        public int Mec { get; set; }
        public int God { get; set; }
        public decimal Sm { get; set; }
        public int Kol { get; set; }
        public int KolObrab { get; set; }
    
        public virtual ICollection<SpisSet> SpisSet { get; set; }
    }
}
