//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpisSet
    {
        public OpisSet()
        {
            this.SpisSet = new HashSet<SpisSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateReg { get; set; }
        public string FileName { get; set; }
        public string Xml { get; set; }
        public string FileName1 { get; set; }
        public string Xml1 { get; set; }
        public string FileName2 { get; set; }
        public string Xml2 { get; set; }
        public string FileName3 { get; set; }
        public string Xml3 { get; set; }
        public string NumMassiv { get; set; }
        public int Mec { get; set; }
        public int God { get; set; }
        public decimal Sm { get; set; }
        public int Kol { get; set; }
        public int KolObrab { get; set; }
    
        public virtual ICollection<SpisSet> SpisSet { get; set; }
    }
}
