//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pfrEntities1 : DbContext
    {
        public pfrEntities1()
            : base("name=pfrEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoSet> DoSet { get; set; }
        public virtual DbSet<OpisSet> OpisSet { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<SpisSet> SpisSet { get; set; }
        public virtual DbSet<TrnSet> TrnSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<TrnSet1> TrnSet1 { get; set; }
    }
}
