//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisSet
    {
        public SpisSet()
        {
            this.TrnSet = new HashSet<TrnSet>();
        }
    
        public int Id { get; set; }
        public int OpisId { get; set; }
        public System.DateTime DateReg { get; set; }
        public string FileName { get; set; }
        public string Xml { get; set; }
        public int mec { get; set; }
        public int god { get; set; }
        public string FileName1 { get; set; }
        public string Xml1 { get; set; }
        public decimal Sm { get; set; }
        public int Kol { get; set; }
        public int NumPart { get; set; }
    
        public virtual OpisSet OpisSet { get; set; }
        public virtual ICollection<TrnSet> TrnSet { get; set; }
    }
}
