//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisSet
    {
        public SpisSet()
        {
            this.TrnSet = new HashSet<TrnSet>();
        }
    
        public int Id { get; set; }
        public int OpisId { get; set; }
        public System.DateTime DateReg { get; set; }
        public string FileName { get; set; }
        public string Xml { get; set; }
        public int mec { get; set; }
        public int god { get; set; }
        public string FileName1 { get; set; }
        public string Xml1 { get; set; }
        public decimal Sm { get; set; }
        public int Kol { get; set; }
        public int NumPart { get; set; }
        public Nullable<int> ITrnNum { get; set; }
    
        public virtual OpisSet OpisSet { get; set; }
        public virtual ICollection<TrnSet> TrnSet { get; set; }
    }
}
