//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnSet1
    {
        public int Id { get; set; }
        public int IdTrn { get; set; }
        public decimal Sm { get; set; }
        public string VidVplPZ { get; set; }
        public string Dt1 { get; set; }
        public string Dt2 { get; set; }
    
        public virtual TrnSet TrnSet { get; set; }
    }
}
