//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnSet1
    {
        public int Id { get; set; }
        public int IdTrn { get; set; }
        public decimal Sm { get; set; }
        public string VidVplPZ { get; set; }
        public string Dt1 { get; set; }
        public string Dt2 { get; set; }
    
        public virtual TrnSet TrnSet { get; set; }
    }
}
