//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfr
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnSet
    {
        public TrnSet()
        {
            this.TrnSet1 = new HashSet<TrnSet1>();
        }
    
        public int Id { get; set; }
        public int IdSpis { get; set; }
        public System.DateTime DateReg { get; set; }
        public string DOffice { get; set; }
        public string Acc { get; set; }
        public decimal Sm { get; set; }
        public string Fam { get; set; }
        public string Imya { get; set; }
        public string Otch { get; set; }
        public Nullable<int> NumInMassiv { get; set; }
        public string NumVplDelo { get; set; }
        public string KodRaiona { get; set; }
        public string StraxNum { get; set; }
        public Nullable<System.DateTime> DFakt { get; set; }
        public string KodZachisl { get; set; }
        public string Acc1 { get; set; }
    
        public virtual SpisSet SpisSet { get; set; }
        public virtual ICollection<TrnSet1> TrnSet1 { get; set; }
    }
}
